name: Deploy React Frontend to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # CRUCIAL FIX: Tell setup-node where to find the package-lock.json
          cache: 'npm' # Specify the package manager for caching
          cache-dependency-path: frontend/package-lock.json # <--- ADD THIS LINE

      - name: Install dependencies and Build React App
        run: |
          npm install
        working-directory: frontend/

      - name: Install dependencies and Build React App
        run: |
          npm ci
          npm run build
        working-directory: frontend/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          publish_branch: gh-pages
          enable_jekyll: false
